name: DgMCPlugin
main: top.DrakGod.DgMCPlugin.Main
version: Beta1.0
api-version: 1.19
description: 这是一个专门为DgMC打造的插件
authors: [Drakgod]
website: https://dgmc.drakgod.top

commands:
  dgmc:
    usage: /dgmc <子指令> [参数]
    aliases: [dgmc]
    description: DgMC插件主指令
    permission: dgmc.commands.dgmc
  help:
    usage: /help [页面]
    aliases: [dghelp]
    description: 查看帮助信息
    permission: dgmc.commands.help
  idbind:
    usage: /idbind <玩家>
    aliases: [bind]
    description: 查看玩家绑定ID
    permission: dgmc.commands.idbind

permissions:
  dgmc.*:
    description: 拥有DgMC插件的所有权限
    default: op
    children:
      dgmc.commands.*: true
  dgmc.commands.*:
    description: 拥有DgMC插件的所有命令权限
    default: true
    children:
      dgmc.commands.dgmc: true
      dgmc.commands.idbind: true
  dgmc.commands.dgmc:
    description: 拥有DgMC插件的/dgmc命令权限
    default: true
  dgmc.commands.help:
    description: 拥有DgMC插件的/help命令权限
    default: true
  dgmc.commands.idbind:
    description: 拥有DgMC插件的/idbind命令权限
    default: true